services:
  jenkins:
    image: jenkins/jenkins:lts
    platform: linux/amd64
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root  # Ensure Jenkins can access Docker
